# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/estelleoliveira/Projet Programmation/PPN/PPN/PPN_CTS"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/estelleoliveira/Projet Programmation/PPN/PPN/PPN_CTS"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/estelleoliveira/Projet Programmation/PPN/PPN/PPN_CTS/CMakeFiles" "/home/estelleoliveira/Projet Programmation/PPN/PPN/PPN_CTS//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/estelleoliveira/Projet Programmation/PPN/PPN/PPN_CTS/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test_Serv

# Build rule for target.
Test_Serv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test_Serv
.PHONY : Test_Serv

# fast build rule for target.
Test_Serv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/build
.PHONY : Test_Serv/fast

#=============================================================================
# Target rules for targets named Test_Cli

# Build rule for target.
Test_Cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test_Cli
.PHONY : Test_Cli

# fast build rule for target.
Test_Cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/build
.PHONY : Test_Cli/fast

#=============================================================================
# Target rules for targets named Serv

# Build rule for target.
Serv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Serv
.PHONY : Serv

# fast build rule for target.
Serv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/build
.PHONY : Serv/fast

#=============================================================================
# Target rules for targets named Cli

# Build rule for target.
Cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cli
.PHONY : Cli

# fast build rule for target.
Cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/build
.PHONY : Cli/fast

src/code/Client.o: src/code/Client.cpp.o
.PHONY : src/code/Client.o

# target to build an object file
src/code/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Client.cpp.o
.PHONY : src/code/Client.cpp.o

src/code/Client.i: src/code/Client.cpp.i
.PHONY : src/code/Client.i

# target to preprocess a source file
src/code/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Client.cpp.i
.PHONY : src/code/Client.cpp.i

src/code/Client.s: src/code/Client.cpp.s
.PHONY : src/code/Client.s

# target to generate assembly for a file
src/code/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Client.cpp.s
.PHONY : src/code/Client.cpp.s

src/code/Crypto.o: src/code/Crypto.cpp.o
.PHONY : src/code/Crypto.o

# target to build an object file
src/code/Crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Crypto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Crypto.cpp.o
.PHONY : src/code/Crypto.cpp.o

src/code/Crypto.i: src/code/Crypto.cpp.i
.PHONY : src/code/Crypto.i

# target to preprocess a source file
src/code/Crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Crypto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Crypto.cpp.i
.PHONY : src/code/Crypto.cpp.i

src/code/Crypto.s: src/code/Crypto.cpp.s
.PHONY : src/code/Crypto.s

# target to generate assembly for a file
src/code/Crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Crypto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Crypto.cpp.s
.PHONY : src/code/Crypto.cpp.s

src/code/Main_Cli.o: src/code/Main_Cli.cpp.o
.PHONY : src/code/Main_Cli.o

# target to build an object file
src/code/Main_Cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Main_Cli.cpp.o
.PHONY : src/code/Main_Cli.cpp.o

src/code/Main_Cli.i: src/code/Main_Cli.cpp.i
.PHONY : src/code/Main_Cli.i

# target to preprocess a source file
src/code/Main_Cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Main_Cli.cpp.i
.PHONY : src/code/Main_Cli.cpp.i

src/code/Main_Cli.s: src/code/Main_Cli.cpp.s
.PHONY : src/code/Main_Cli.s

# target to generate assembly for a file
src/code/Main_Cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Main_Cli.cpp.s
.PHONY : src/code/Main_Cli.cpp.s

src/code/Main_Serv.o: src/code/Main_Serv.cpp.o
.PHONY : src/code/Main_Serv.o

# target to build an object file
src/code/Main_Serv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Main_Serv.cpp.o
.PHONY : src/code/Main_Serv.cpp.o

src/code/Main_Serv.i: src/code/Main_Serv.cpp.i
.PHONY : src/code/Main_Serv.i

# target to preprocess a source file
src/code/Main_Serv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Main_Serv.cpp.i
.PHONY : src/code/Main_Serv.cpp.i

src/code/Main_Serv.s: src/code/Main_Serv.cpp.s
.PHONY : src/code/Main_Serv.s

# target to generate assembly for a file
src/code/Main_Serv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Main_Serv.cpp.s
.PHONY : src/code/Main_Serv.cpp.s

src/code/SRD-BTC.o: src/code/SRD-BTC.cpp.o
.PHONY : src/code/SRD-BTC.o

# target to build an object file
src/code/SRD-BTC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/SRD-BTC.cpp.o
.PHONY : src/code/SRD-BTC.cpp.o

src/code/SRD-BTC.i: src/code/SRD-BTC.cpp.i
.PHONY : src/code/SRD-BTC.i

# target to preprocess a source file
src/code/SRD-BTC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/SRD-BTC.cpp.i
.PHONY : src/code/SRD-BTC.cpp.i

src/code/SRD-BTC.s: src/code/SRD-BTC.cpp.s
.PHONY : src/code/SRD-BTC.s

# target to generate assembly for a file
src/code/SRD-BTC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/SRD-BTC.cpp.s
.PHONY : src/code/SRD-BTC.cpp.s

src/code/Server.o: src/code/Server.cpp.o
.PHONY : src/code/Server.o

# target to build an object file
src/code/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Server.cpp.o
.PHONY : src/code/Server.cpp.o

src/code/Server.i: src/code/Server.cpp.i
.PHONY : src/code/Server.i

# target to preprocess a source file
src/code/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Server.cpp.i
.PHONY : src/code/Server.cpp.i

src/code/Server.s: src/code/Server.cpp.s
.PHONY : src/code/Server.s

# target to generate assembly for a file
src/code/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Server.cpp.s
.PHONY : src/code/Server.cpp.s

src/code/Transaction.o: src/code/Transaction.cpp.o
.PHONY : src/code/Transaction.o

# target to build an object file
src/code/Transaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Transaction.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Transaction.cpp.o
.PHONY : src/code/Transaction.cpp.o

src/code/Transaction.i: src/code/Transaction.cpp.i
.PHONY : src/code/Transaction.i

# target to preprocess a source file
src/code/Transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Transaction.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Transaction.cpp.i
.PHONY : src/code/Transaction.cpp.i

src/code/Transaction.s: src/code/Transaction.cpp.s
.PHONY : src/code/Transaction.s

# target to generate assembly for a file
src/code/Transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/Transaction.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/Transaction.cpp.s
.PHONY : src/code/Transaction.cpp.s

src/code/bot.o: src/code/bot.cpp.o
.PHONY : src/code/bot.o

# target to build an object file
src/code/bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/bot.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/bot.cpp.o
.PHONY : src/code/bot.cpp.o

src/code/bot.i: src/code/bot.cpp.i
.PHONY : src/code/bot.i

# target to preprocess a source file
src/code/bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/bot.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/bot.cpp.i
.PHONY : src/code/bot.cpp.i

src/code/bot.s: src/code/bot.cpp.s
.PHONY : src/code/bot.s

# target to generate assembly for a file
src/code/bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/bot.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/bot.cpp.s
.PHONY : src/code/bot.cpp.s

src/code/global.o: src/code/global.cpp.o
.PHONY : src/code/global.o

# target to build an object file
src/code/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/global.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/global.cpp.o
.PHONY : src/code/global.cpp.o

src/code/global.i: src/code/global.cpp.i
.PHONY : src/code/global.i

# target to preprocess a source file
src/code/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/global.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/global.cpp.i
.PHONY : src/code/global.cpp.i

src/code/global.s: src/code/global.cpp.s
.PHONY : src/code/global.s

# target to generate assembly for a file
src/code/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Serv.dir/build.make CMakeFiles/Test_Serv.dir/src/code/global.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_Cli.dir/build.make CMakeFiles/Test_Cli.dir/src/code/global.cpp.s
.PHONY : src/code/global.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cli"
	@echo "... Serv"
	@echo "... Test_Cli"
	@echo "... Test_Serv"
	@echo "... src/code/Client.o"
	@echo "... src/code/Client.i"
	@echo "... src/code/Client.s"
	@echo "... src/code/Crypto.o"
	@echo "... src/code/Crypto.i"
	@echo "... src/code/Crypto.s"
	@echo "... src/code/Main_Cli.o"
	@echo "... src/code/Main_Cli.i"
	@echo "... src/code/Main_Cli.s"
	@echo "... src/code/Main_Serv.o"
	@echo "... src/code/Main_Serv.i"
	@echo "... src/code/Main_Serv.s"
	@echo "... src/code/SRD-BTC.o"
	@echo "... src/code/SRD-BTC.i"
	@echo "... src/code/SRD-BTC.s"
	@echo "... src/code/Server.o"
	@echo "... src/code/Server.i"
	@echo "... src/code/Server.s"
	@echo "... src/code/Transaction.o"
	@echo "... src/code/Transaction.i"
	@echo "... src/code/Transaction.s"
	@echo "... src/code/bot.o"
	@echo "... src/code/bot.i"
	@echo "... src/code/bot.s"
	@echo "... src/code/global.o"
	@echo "... src/code/global.i"
	@echo "... src/code/global.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

